### ISSUE TITLE
Question about reload approach

### ISSUE THREAD

**Issue by atiniir** [wcm-io-devops/ansible-jenkins-configuration-as-code#16]
Sorry for making an issue, I couldn't figure out another way to send in a question :/ 

I'm curious about the reload approach you are using, as compared to using the CASC_RELOAD_TOKEN approach described https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/configurationReload.md particularly given the linked page specifically mentions the groovy script approach is not recommended with the added context "Note: that running the above code in a pipeline will put this plugin in a bad state where the configuration cannot be reloaded at all until Jenkins is restarted. See https://github.com/jenkinsci/configuration-as-code-plugin/issues/1227 for more info." 

I suspect part of the reason is that CASC_RELOAD_TOKEN didn't exist before and/or was hard to use.  But I'm also wondering if there is another advantage to the approach you are using and I'm just not seeing it. 

Thanks!

**Comment by tobias-richter** [comment]
Hi @atiniir we are reloading this by executing a groovy script on the instance and not from within a pipeline, see

https://github.com/wcm-io-devops/ansible-jenkins-configuration-as-code/blob/master/tasks/reload.yml and
https://github.com/wcm-io-devops/ansible-jenkins-configuration-as-code/blob/master/files/groovy/jcasc/reload.groovy

Until now we have not experienced any issues with this approach.

**Comment by atiniir** [comment]
awesome thanks for the insight!
