### ISSUE TITLE
changed github user from wcm_io_devops to wcm-io-devops??

### ISSUE THREAD

**Issue by manelso** [wcm-io-devops/ansible-jenkins-configuration-as-code#19]
Hi,

Have you changed the owner user from your repositories?

I've been using your roles from more than a year ago, and today I've started to get the following error when installing your role "jenkins_configuration_as_code":
```
- downloading role 'jenkins_configuration_as_code', owned by wcm_io_devops
- downloading role from https://github.com/wcm_io_devops/ansible-jenkins-configuration-as-code/archive/1.13.0.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found
[WARNING]: - wcm_io_devops.jenkins_configuration_as_code was NOT installed successfully.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

I've tried to point to what I've supposed that is the correct URL and this solved the error but I've started to receive a new error when trying to download the role wcm_io_devops.jenkins_plugins used by ansible-jenkins-configuration-as-code ...

Thanks

**Comment by manelso** [comment]
Maybe the problem is related with the last update in ansible galaxy web:
https://galaxy.ansible.com/ui/standalone/roles/wcm_io_devops/jenkins_configuration_as_code/

It seems to be that github link is pointing to an incorrect repo...
![image](https://github.com/wcm-io-devops/ansible-jenkins-configuration-as-code/assets/25355743/35b678cb-f858-4753-b890-faf10fc8ccc6)

**Comment by manelsanchez-scopely** [comment]
I've done a workaround changing the role installation in requirements.yml by this code:
  - name: wcm_io_devops.jenkins_facts
    src: https://github.com/wcm-io-devops/ansible-jenkins-facts
    version: 1.3.2
  - name: wcm_io_devops.jenkins_service
    src: https://github.com/wcm-io-devops/ansible-jenkins-service
    version: 1.2.2
  - name: wcm_io_devops.jenkins_plugins
    src: https://github.com/wcm-io-devops/ansible-jenkins-plugins
    version: 1.5.1
  - name: wcm_io_devops.jenkins_configuration_as_code
    src: https://github.com/wcm-io-devops/ansible-jenkins-configuration-as-code
    version: 1.13.0

**Comment by tobias-richter** [comment]
Hi @manelso we also encountering this issue with the launch of the new Ansible Galaxy NG were the path to the archives are wrongly calculated.
For now explicitely defining the dependencies is the only way I know.

**Comment by tobias-richter** [comment]
@manelso see https://github.com/ansible/galaxy_ng/pull/1923
